### ISSUE TITLE
Windows下的Docker 安装 悟空IM，说找不到image。。请问怎么处理。

### ISSUE THREAD

**Issue by wangcaiokNew** [WuKongIM/WuKongIMJSSDK#1]
![ab87b6baa0da10119bd2ce3f967a2a6](https://github.com/WuKongIM/WuKongIMJSSDK/assets/13728431/ccd8b48f-4bd1-4939-9a5d-9ef96793ee28)

Unable to find image 'wukongim/wukongim:latest' locally
latest: Pulling from wukongim/wukongim
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.

**Comment by tangtaoit** [comment]
你这问题不是找不到image是 `docker: image operating system "linux" cannot be used on this platform.`，参考： https://blog.csdn.net/qq_38410428/article/details/82726050
