### ISSUE TITLE
vue2的情况下获取到频道信息后视图不刷新

### ISSUE THREAD

**Issue by Super-jie6** [WuKongIM/WuKongIMJSSDK#10]
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/9d8722b6-3037-4e83-b2c9-b04933c4aadd)
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/29a0d9c5-20a4-432e-a456-5b306d1cdb80)
构造Conversation会话里的channelInfo只可读触发的这个问题吗

**Comment by tangtaoit** [comment]
WKSDK.shared().channelManager.addListener(channelInfoListener)   有没有在监听器里重新触发渲染？

参考：
https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/components/Conversation/index.vue#L54
