### ISSUE TITLE
删除会话没有触发监听最近会话的回调

### ISSUE THREAD

**Issue by Super-jie6** [WuKongIM/WuKongIMJSSDK#11]
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/3c9371bf-d633-48c8-959e-cf4ce0c02dc3)
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/f4b876e2-dc75-4c4d-b114-e8159c9edaa4)这两者方法都试过并没有触发到监听回调，会话的新建和更新都能监听到
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/3e28e963-f4b3-4250-ade3-dec88f05be30)

**Comment by tangtaoit** [comment]
这个需要你自己业务端下发cmd给客户端，然后客户端收到后进行本地清除才会触发。

解决方案：

1. 你们业务端 通过` /message/send` api发送 cmd消息，定义一个唯一的cmd命令,具体格式参考：https://githubim.com/guide/proto.html#%E5%91%BD%E4%BB%A4%E6%B6%88%E6%81%AF

2. 你们客户端收到此指令后，执行 `WKSDK.shared().conversationManager.removeConversation(channel)` 移除对应的会话，这个方法就会触发监听
