### ISSUE TITLE
jssdk能加一下消息本地存储的能力吗

### ISSUE THREAD

**Issue by zyh819heng** [WuKongIM/WuKongIMJSSDK#13]
目前pc/web没有消息本地存储功能（切换聊天都是要走消息同步的接口）这样用户来回切换流量消耗大而且网络不好的情况需要卡个半秒到一秒，app端切换不同聊天窗口非常流畅的希望pc/web也有本地消息存储的能力呢

**Comment by tangtaoit** [comment]
pc/web一般网络流畅，WuKongIM的接口是<毫秒级别的, 考虑几下几点不做本地存储。 app端有做本地存储。
