### ISSUE TITLE
自定义调整之后，怎么通过npm lik或者其他方式引用到Web项目中

### ISSUE THREAD

**Issue by helloworldoc** [WuKongIM/WuKongIMJSSDK#14]
尝试了下使用npm link会出现图片上的错误
![微信图片_20241117102829](https://github.com/user-attachments/assets/089e3b39-fdb2-4c9d-ae91-eb1b0cd6ce88)

**Comment by tangtaoit** [comment]
依赖bignumber.js没有add吧？

**Comment by helloworldoc** [comment]
wukongimjssdk里面有依赖，都是可以build和test，我想通过本地引入到web使用
