### ISSUE TITLE
发送消息时报错

### ISSUE THREAD

**Issue by Super-jie6** [WuKongIM/WuKongIMJSSDK#9]
![image](https://github.com/WuKongIM/WuKongIMJSSDK/assets/58161070/6d449b66-5b84-4cd3-87a1-33c570f45ff2)

**Comment by tangtaoit** [comment]
调用服务器后 应该返回sdk一个 Conversation对象 而不是any对象

参考：

https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/services/APIClient.ts#L164

https://github.com/WuKongIM/WuKongIMJSSDK/blob/main/examples/src/services/convert.ts#L78

 const conversation = new Conversation()
